import { Inter } from 'next/font/google';
import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Ecosolution',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head></head>
      <body
        style={{
          position: 'relative',
        }}
        className={inter.className}
      >
        {children}
      </body>
    </html>
  );
}
